name: flutter_minesweeper
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ^3.13.0

dependencies:
  cloud_firestore: ^4.8.4
  cloud_firestore_odm: ^1.0.0-dev.64
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.10
  freezed_annotation: ^2.4.1
  go_router: ^11.1.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.6
  cloud_firestore_odm_generator: ^1.0.0-dev.64
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  lint: ^2.0.0
  riverpod_generator: ^2.3.1
  riverpod_lint: ^2.0.3

flutter:
  uses-material-design: true
