name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          cache: true

      - run: flutter pub get

      - run: dart run build_runner build --delete-conflicting-outputs

      - run: flutter analyze
      - run: dart run custom_lint

      - run: flutter test

      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /${{ github.event.repository.name }}/
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
